title: huanggang
description: My Personal Blog
tagline: Site Tagline

# 个人信息
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname
  
logo: /NanGangHuang.github.io/static/img/avatar.png
github: https://github.com/NanGangHuang
about: Java developer

baseurl: "https://nanganghuang.github.io"
url: "https://nanganghuang.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

# 
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
